version: '3'
services:
  frontend:
    image: buildbarn/bb-storage:20200102T100452Z-f920d92
    command:
    - /config/frontend.jsonnet
    ports:
    - 7980:7980
    - 8980:8980
    volumes:
    - ./config:/config

  storage-0:
    image: buildbarn/bb-storage:20200102T100452Z-f920d92
    command:
    - /config/storage.jsonnet
    expose:
    - 8981
    ports:
    - 7981:7981
    volumes:
    - ./config:/config
    - ./storage-ac-0:/storage-ac
    - ./storage-cas-0:/storage-cas
  storage-1:
    image: buildbarn/bb-storage:20200102T100452Z-f920d92
    command:
    - /config/storage.jsonnet
    expose:
    - 8981
    ports:
    - 17981:7981
    volumes:
    - ./config:/config
    - ./storage-ac-1:/storage-ac
    - ./storage-cas-1:/storage-cas

  scheduler:
    image: buildbarn/bb-scheduler:20200102T102244Z-300a067
    command:
    - /config/scheduler.jsonnet
    expose:
    - 8982
    - 8983
    ports:
    - 7982:7982
    volumes:
    - ./config:/config
  browser:
    image: buildbarn/bb-browser:20200102T103638Z-e432c91
    command:
    - /config/browser.jsonnet
    ports:
    - 7984:7984
    volumes:
    - ./config:/config
  event-service:
    image: buildbarn/bb-event-service:20200102T104139Z-c01f79c
    command:
    - /config/event-service.jsonnet
    ports:
    - 7985:7985
    - 8985:8985
    volumes:
    - ./config:/config

  worker-ubuntu16-04:
    image: buildbarn/bb-worker:20200102T102244Z-300a067
    command:
    - /config/worker-ubuntu16-04.jsonnet
    ports:
    - 7986:7986
    volumes:
    - ./config:/config
    - ./worker-ubuntu16-04:/worker
  runner-ubuntu16-04:
    image: buildbarn/bb-runner-ubuntu16-04:20200102T102244Z-300a067
    command:
    - /config/runner-ubuntu16-04.jsonnet
    network_mode: none
    volumes:
    - ./worker-ubuntu16-04:/worker
    - ./config:/config
