version: '3'
services:
  frontend:
    image: buildbarn/bb-storage:20190211T175559Z-ee2cb65
    command:
    - -scheduler=debian8|scheduler-debian8:8981
    - -scheduler=ubuntu16-04|scheduler-ubuntu16-04:8981
    ports:
    - 7980:80
    - 8980:8980
    volumes:
    - ./config-storage-clients:/config

  storage-0:
    image: buildbarn/bb-storage:20190211T175559Z-ee2cb65
    command:
    - -allow-ac-updates-for-instance=debian8
    - -allow-ac-updates-for-instance=ubuntu16-04
    expose:
    - 8980
    ports:
    - 7982:80
    volumes:
    - ./config-storage:/config
    - ./storage-ac-0:/storage-ac
    - ./storage-cas-0:/storage-cas
  storage-1:
    image: buildbarn/bb-storage:20190211T175559Z-ee2cb65
    command:
    - -allow-ac-updates-for-instance=debian8
    - -allow-ac-updates-for-instance=ubuntu16-04
    expose:
    - 8980
    ports:
    - 17982:80
    volumes:
    - ./config-storage:/config
    - ./storage-ac-1:/storage-ac
    - ./storage-cas-1:/storage-cas

  browser:
    image: buildbarn/bb-browser:20190210T072316Z-0f6bc13
    ports:
    - 7983:80
    volumes:
    - ./config-storage-clients:/config

  scheduler-debian8:
    image: buildbarn/bb-scheduler:20190210T161704Z-6f6bded
    expose:
    - 8981
    ports:
    - 7981:80
  worker-debian8:
    image: buildbarn/bb-worker:20190210T161704Z-6f6bded
    command:
    - -browser-url=http://localhost:7983/
    - -concurrency=4
    - -scheduler=scheduler-debian8:8981
    ports:
    - 7984:80
    volumes:
    - ./config-storage-clients:/config
    - ./worker-debian8:/worker
  runner-debian8:
    image: buildbarn/bb-runner-debian8:20190210T161704Z-6f6bded
    network_mode: none
    volumes:
    - ./worker-debian8:/worker

  scheduler-ubuntu16-04:
    image: buildbarn/bb-scheduler:20190210T161704Z-6f6bded
    expose:
    - 8981
    ports:
    - 17981:80
  worker-ubuntu16-04:
    image: buildbarn/bb-worker:20190210T161704Z-6f6bded
    command:
    - -browser-url=http://localhost:7983/
    - -concurrency=4
    - -scheduler=scheduler-ubuntu16-04:8981
    ports:
    - 17984:80
    volumes:
    - ./config-storage-clients:/config
    - ./worker-ubuntu16-04:/worker
  runner-ubuntu16-04:
    image: buildbarn/bb-runner-ubuntu16-04:20190210T161704Z-6f6bded
    network_mode: none
    volumes:
    - ./worker-ubuntu16-04:/worker
