version: '3'
services:
  frontend:
    image: buildbarn/bb-storage:20190211T175559Z-ee2cb65
    command:
    - /config/frontend.json
    ports:
    - 7980:80
    - 8980:8980
    volumes:
    - ./config:/config

  storage-0:
    image: buildbarn/bb-storage:20190211T175559Z-ee2cb65
    command:
    - /config/storage.json
    expose:
    - 8980
    ports:
    - 7982:80
    volumes:
    - ./config:/config
    - ./storage-ac-0:/storage-ac
    - ./storage-cas-0:/storage-cas
  storage-1:
    image: buildbarn/bb-storage:20190211T175559Z-ee2cb65
    command:
    - /config/storage.json
    expose:
    - 8980
    ports:
    - 17982:80
    volumes:
    - ./config:/config
    - ./storage-ac-1:/storage-ac
    - ./storage-cas-1:/storage-cas

  event-service:
    image: buildbarn/bb-event-service:20190225T222112Z-b9170c2
    command:
    - /config/event-service.json
    ports:
    - 7983:80
    - 8983:8983
    volumes:
    - ./config:/config
  browser:
    image: buildbarn/bb-browser:20190303T064412Z-dd7ac26
    command:
    - /config/browser.json
    ports:
    - 7984:80
    volumes:
    - ./config:/config

  scheduler-debian8:
    image: buildbarn/bb-scheduler:20190210T161704Z-6f6bded
    expose:
    - 8981
    ports:
    - 7981:80
  worker-debian8:
    image: buildbarn/bb-worker:20190210T161704Z-6f6bded
    command:
    - /config/worker-debian8.json
    ports:
    - 7985:80
    volumes:
    - ./config:/config
    - ./worker-debian8:/worker
  runner-debian8:
    image: buildbarn/bb-runner-debian8:20190210T161704Z-6f6bded
    network_mode: none
    volumes:
    - ./worker-debian8:/worker

  scheduler-ubuntu16-04:
    image: buildbarn/bb-scheduler:20190210T161704Z-6f6bded
    expose:
    - 8981
    ports:
    - 17981:80
  worker-ubuntu16-04:
    image: buildbarn/bb-worker:20190210T161704Z-6f6bded
    command:
    - /config/worker-ubuntu16-04.json
    ports:
    - 17985:80
    volumes:
    - ./config:/config
    - ./worker-ubuntu16-04:/worker
  runner-ubuntu16-04:
    image: buildbarn/bb-runner-ubuntu16-04:20190210T161704Z-6f6bded
    network_mode: none
    volumes:
    - ./worker-ubuntu16-04:/worker
