apiVersion: v1
data:
  worker.json: |
    {
      "blobstore": {
        "contentAddressableStorage": {
          "sharding": {
            "hashInitialization": 11946695773637837490,
            "shard": [
              {
                "backend": {
                  "grpc": {
                    "endpoint": "storage-0.storage:8980"
                  }
                },
                "weight": 1
              },
              {
                "backend": {
                  "grpc": {
                    "endpoint": "storage-1.storage:8980"
                  }
                },
                "weight": 1
              },
              {
                "backend": {
                  "grpc": {
                    "endpoint": "storage-2.storage:8980"
                  }
                },
                "weight": 1
              }
            ]
          }
        },
        "actionCache": {
          "sharding": {
            "hashInitialization": 14897363947481274433,
            "shard": [
              {
                "backend": {
                  "grpc": {
                    "endpoint": "storage-0.storage:8980"
                  }
                },
                "weight": 1
              },
              {
                "backend": {
                  "grpc": {
                    "endpoint": "storage-1.storage:8980"
                  }
                },
                "weight": 1
              },
              {
                "backend": {
                  "grpc": {
                    "endpoint": "storage-2.storage:8980"
                  }
                },
                "weight": 1
              }
            ]
          }
        }
      },
      "browserUrl": "http://bb-browser.example.com/",
      "concurrency": 4,
      "schedulerAddress": "scheduler-debian8:8981"
    }
kind: ConfigMap
metadata:
  name: worker-debian8
  namespace: buildbarn
