apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: buildbarn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - args:
        - -scheduler=debian8|scheduler-debian8:8981
        - -scheduler=ubuntu16-04|scheduler-ubuntu16-04:8981
        image: buildbarn/bb-storage:20190211T175559Z-ee2cb65
        name: storage
        ports:
        - containerPort: 8980
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          defaultMode: 400
          name: config-storage-clients
        name: config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: frontend
  namespace: buildbarn
spec:
  ports:
  - port: 8980
    protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer
